// Auto-generated by scripts/infer-voice.mjs. Edit by hand only if the inferred
// voice misrepresents the brand; otherwise rerun the script.
//
// Sampled 10 articles on 2026-04-17:
//   - hiit-vs-steady-state-cardio
//   - calorie-counting-for-beginners
//   - optimum-nutrition-gold-standard-whey-review
//   - best-multivitamins-athletes
//   - how-to-sleep-better-athletes
//   - best-high-protein-foods-muscle-fat-loss
//   - home-workout-guide-for-beginners-30-days
//   - intermittent-fasting-for-beginners-16-8
//   - resistance-band-workout-12-exercises
//   - compound-vs-isolation-exercises

export const BRAND_VOICE = `Write like an experienced, no-nonsense fitness mentor who is highly knowledgeable but prioritizes clear, practical, and evidence-backed advice, fostering a relationship of informed trust with the reader. Employ direct, concise language with a mix of sentence lengths, frequently incorporating specific data, percentages, and scientific citations to support claims, while utilizing bolding and structured formatting for scannability. Avoid hyperbolic "bro-science" language, unsupported claims, or vague generalities, instead focusing on clear explanations and a realistic, non-judgmental tone that steers clear of "miracle cure" framing.`;
