#!/usr/bin/env node
// Infer brand voice from existing MDX articles and write it to lib/social/voice.ts.
//
// Run: node --env-file=.env.local scripts/infer-voice.mjs
//
// Requires: GOOGLE_GENERATIVE_AI_API_KEY in .env.local
// Get a free key at https://aistudio.google.com/app/apikey

import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";
import { generateText } from "ai";
import { google } from "@ai-sdk/google";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const ARTICLES_DIR = join(ROOT, "content", "articles");
const OUT_FILE = join(ROOT, "lib", "social", "voice.ts");

const SAMPLE_SIZE = 10;
const MODEL_ID = "gemini-2.5-flash";

function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

async function loadSample() {
  const files = (await readdir(ARTICLES_DIR)).filter((f) => f.endsWith(".mdx"));
  if (files.length < SAMPLE_SIZE) {
    throw new Error(
      `Only ${files.length} articles in ${ARTICLES_DIR}; need at least ${SAMPLE_SIZE}.`,
    );
  }
  const picked = shuffle(files).slice(0, SAMPLE_SIZE);
  const samples = [];
  for (const f of picked) {
    const raw = await readFile(join(ARTICLES_DIR, f), "utf8");
    const { content, data } = matter(raw);
    // Trim body to ~3000 chars to keep the combined prompt tractable.
    const body = content.trim().slice(0, 3000);
    samples.push({ slug: f.replace(/\.mdx$/, ""), title: data.title, body });
  }
  return samples;
}

function buildPrompt(samples) {
  const excerpts = samples
    .map(
      (s, i) =>
        `<<<EXCERPT_${i + 1} slug="${s.slug}" title="${s.title}">>>\n${s.body}\n<<<END_EXCERPT_${i + 1}>>>`,
    )
    .join("\n\n");

  return `Below are ${samples.length} excerpts from a fitness/wellness blog. Analyze the consistent writing voice across them.

${excerpts}

Return exactly 3 sentences describing the voice as if briefing a copywriter. Cover:
1. Tone & persona — who does the writing sound like, and what is their relationship to the reader?
2. Diction & sentence rhythm — word choice, paragraph length, use of numbers/specifics.
3. What it avoids — phrases, clichés, or postures you should not copy.

Write in second person ("Write like…", "Avoid…"). No preamble, no closing remarks, just the 3 sentences.`;
}

async function main() {
  console.log(`[infer-voice] sampling ${SAMPLE_SIZE} articles from ${ARTICLES_DIR}`);
  const samples = await loadSample();
  console.log(`[infer-voice] samples: ${samples.map((s) => s.slug).join(", ")}`);

  console.log(`[infer-voice] calling Google ${MODEL_ID}…`);
  const { text, usage } = await generateText({
    model: google(MODEL_ID),
    prompt: buildPrompt(samples),
  });

  const voice = text.trim();
  console.log(`\n[infer-voice] inferred voice:\n---\n${voice}\n---\n`);
  console.log(`[infer-voice] tokens: ${JSON.stringify(usage)}`);

  await mkdir(dirname(OUT_FILE), { recursive: true });
  const fileBody = `// Auto-generated by scripts/infer-voice.mjs. Edit by hand only if the inferred
// voice misrepresents the brand; otherwise rerun the script.
//
// Sampled ${samples.length} articles on ${new Date().toISOString().slice(0, 10)}:
${samples.map((s) => `//   - ${s.slug}`).join("\n")}

export const BRAND_VOICE = \`${voice.replace(/`/g, "\\`")}\`;
`;
  await writeFile(OUT_FILE, fileBody, "utf8");
  console.log(`[infer-voice] wrote ${OUT_FILE}`);
}

main().catch((err) => {
  console.error("[infer-voice] failed:", err);
  process.exit(1);
});
