#!/usr/bin/env node
/**
 * rebrand.mjs — generate lib/brand.ts from client.config.json
 *
 * Usage:
 *   cp client.config.example.json client.config.json
 *   # edit client.config.json with the new client's values
 *   node scripts/rebrand.mjs
 *
 * Writes lib/brand.ts in the shape expected by the codebase. If the target
 * file already exists, it's overwritten — keep the original under version
 * control so you can diff before committing.
 */

import fs from "node:fs";
import path from "node:path";
import url from "node:url";

const root = path.resolve(path.dirname(url.fileURLToPath(import.meta.url)), "..");
const CONFIG_PATH = path.join(root, "client.config.json");
const TARGET_PATH = path.join(root, "lib", "brand.ts");
const EXAMPLE_PATH = path.join(root, "client.config.example.json");

const ALLOWED_PLATFORMS = new Set([
  "instagram",
  "youtube",
  "tiktok",
  "x",
  "threads",
  "facebook",
]);

function fail(msg) {
  console.error(`\u2717 ${msg}`);
  process.exit(1);
}

function ok(msg) {
  console.log(`\u2713 ${msg}`);
}

if (!fs.existsSync(CONFIG_PATH)) {
  fail(
    `Missing client.config.json. Copy ${path.relative(root, EXAMPLE_PATH)} to client.config.json, fill it in, then rerun.`,
  );
}

let config;
try {
  config = JSON.parse(fs.readFileSync(CONFIG_PATH, "utf8"));
} catch (err) {
  fail(`client.config.json is not valid JSON: ${err.message}`);
}

// Validation —
const required = [
  "name",
  "shortName",
  "tagline",
  "description",
  "legalName",
  "author",
  "contact",
  "affiliates",
  "socials",
];
for (const key of required) {
  if (config[key] === undefined || config[key] === null) {
    fail(`client.config.json is missing required field: ${key}`);
  }
}

const authorRequired = ["name", "bio", "photoUrl", "profileUrl", "emitPersonSchema"];
for (const key of authorRequired) {
  if (config.author[key] === undefined) {
    fail(`client.config.json.author is missing required field: ${key}`);
  }
}

if (typeof config.affiliates.amazonTag !== "string" || config.affiliates.amazonTag.length === 0) {
  fail(`client.config.json.affiliates.amazonTag must be a non-empty string (Amazon Associates tracking ID).`);
}

if (!Array.isArray(config.socials)) {
  fail(`client.config.json.socials must be an array (possibly empty).`);
}
for (const [i, s] of config.socials.entries()) {
  if (!s.platform || !ALLOWED_PLATFORMS.has(s.platform)) {
    fail(
      `socials[${i}].platform "${s.platform}" is not a supported platform. Allowed: ${[...ALLOWED_PLATFORMS].join(", ")}`,
    );
  }
  if (!s.handle || !s.url) {
    fail(`socials[${i}] is missing handle or url.`);
  }
}

// Normalize —
function clean(s) {
  return typeof s === "string" ? s.trim() : s;
}

const brand = {
  name: clean(config.name),
  shortName: clean(config.shortName),
  tagline: clean(config.tagline),
  description: clean(config.description),
  legalName: clean(config.legalName),
  author: {
    name: clean(config.author.name),
    ...(config.author.credentials
      ? { credentials: clean(config.author.credentials) }
      : {}),
    bio: clean(config.author.bio),
    ...(config.author.longBio ? { longBio: clean(config.author.longBio) } : {}),
    photoUrl: config.author.photoUrl === null ? null : clean(config.author.photoUrl),
    profileUrl: clean(config.author.profileUrl),
    ...(Array.isArray(config.author.knowsAbout) && config.author.knowsAbout.length > 0
      ? { knowsAbout: config.author.knowsAbout.map(clean) }
      : {}),
    emitPersonSchema: Boolean(config.author.emitPersonSchema),
  },
  contact: {
    email: clean(config.contact.email),
  },
  affiliates: {
    amazonTag: clean(config.affiliates.amazonTag),
    clickbankId: config.affiliates.clickbankId
      ? clean(config.affiliates.clickbankId)
      : null,
    shareasaleId: config.affiliates.shareasaleId
      ? clean(config.affiliates.shareasaleId)
      : null,
  },
  socials: config.socials.map((s) => ({
    platform: s.platform,
    handle: clean(s.handle),
    url: clean(s.url),
  })),
};

// Code generation —
// Re-emit using the same shape as the hand-written file so diffs are minimal
// and the import surface stays identical.
const source = `/**
 * Single source of truth for per-client branding.
 *
 * Generated by scripts/rebrand.mjs from client.config.json. Hand edits will
 * be overwritten on the next rebrand — update client.config.json instead and
 * rerun the script.
 *
 * See docs/CLIENT_SETUP.md for the full onboarding workflow.
 */

export type SocialLink = {
  platform: "instagram" | "youtube" | "tiktok" | "x" | "threads" | "facebook";
  handle: string;
  url: string;
};

export type BrandAuthor = {
  /** Name used in bylines, schema.org Person.name, and metadata. */
  name: string;
  /** Short title (e.g., "CSCS, RD"). Mapped to Person.jobTitle when present. */
  credentials?: string;
  /** 1–3 sentence bio used on article cards and AuthorCard compact variant. */
  bio: string;
  /** Extended multi-paragraph bio for the /about hero. Falls back to bio. */
  longBio?: string;
  /** Square author photo URL, or null to render a monogram fallback. */
  photoUrl: string | null;
  /** Canonical profile page URL on this site (usually "/about"). */
  profileUrl: string;
  /** Topics the author covers — maps to schema.org Person.knowsAbout. */
  knowsAbout?: string[];
  /** When true, articles emit Person (influencer) as author; else Organization. */
  emitPersonSchema: boolean;
};

export type BrandAffiliates = {
  /** Amazon Associates tracking ID. Appended to every amazon.com product link. */
  amazonTag: string;
  /** ClickBank nickname. Null if unused. */
  clickbankId: string | null;
  /** ShareASale affiliate ID. Null if unused. */
  shareasaleId: string | null;
};

export type BrandContact = {
  email: string;
};

export type Brand = {
  name: string;
  shortName: string;
  tagline: string;
  description: string;
  legalName: string;
  author: BrandAuthor;
  contact: BrandContact;
  affiliates: BrandAffiliates;
  socials: SocialLink[];
};

export const brand: Brand = ${JSON.stringify(brand, null, 2)};
`;

fs.writeFileSync(TARGET_PATH, source, "utf8");

ok(`Wrote ${path.relative(root, TARGET_PATH)}`);
ok(`Brand: ${brand.name} (${brand.shortName})`);
ok(`Author: ${brand.author.name}${brand.author.emitPersonSchema ? " — Person schema ON" : " — Organization fallback"}`);
ok(`Amazon tag: ${brand.affiliates.amazonTag}`);
ok(`Socials: ${brand.socials.length === 0 ? "(none)" : brand.socials.map((s) => s.platform).join(", ")}`);

console.log(`\nNext steps:\n  1. Review git diff on lib/brand.ts\n  2. Drop the client's author photo at ${brand.author.photoUrl ?? "(photoUrl is null — set it in client.config.json if you have one)"}\n  3. Set env vars in Vercel (see docs/CLIENT_SETUP.md step 3)\n  4. Commit and push\n`);
